### ISSUE TITLE
Why not Emscripten?

### ISSUE THREAD

**Issue by Querijn** [Slynchy/March22-JS#1]
Seeing as your original engine was in C++, you could make an emscripten build. It supports SDL, so you got that part covered.. Might save you some time?

**Comment by Slynchy** [comment]
Sadly the only part of the C++ version that isn't too out of date is the script compiler, which was just ported yesterday 😒 

However Emscripten looks to be exactly what I've been looking for for writing binary file loaders, cheers for the tip!

**Comment by Querijn** [comment]
Alternatively, there's Cheerp, but it's a bit different and I have no experience with it. Might be a totally different experience. Good luck!
